dist: xenial
language: python

python:
  - 3.9

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - echo "Skipping tests"

deploy:
  provider: pypi
  username: noraa-july-stoke
  password:
    secure: "pypi-AgEIcHlwaS5vcmcCJDgxODhmOWNhLTM4ODEtNDQ5MS1hNTUyLTBmNWEyN2UxMzIxZAACKlszLCI4NTE1NTQ2ZS03MTYzLTQ5ZTAtYWQ1Zi01OWYxMTM4ZWMzM2QiXQAABiD4-Cqwdx-VLFBZIjb9Xy3qAj4rZuswkVT6djBGDfgZOg"
  on:
    branch: main
  distributions: bdist_wheel
  skip_cleanup: true
