dist: bionic
language: python
python:
- 3.9.7
install:
- pip install pipenv
script:
- echo "Skipping tests"
deploy:
  provider: pypi
  username: __token__
  password:
    secure: SxxLIhTEzJ4ya7bWOtptVib3A/lSB1rGi0NPbKYqUFBxV6zPfd1HCpVx4mR15d5jltk6T/9h7CI8twDk/cWoaumYSkJHet9mTmklrGdKZGrKA531nCW1UqwQAQTBgZVTeZTXmix7/DDZxRHR31rIOJ1lBAz3D+ibsfK0m8wdx7sRX3Tey49/MCwraNsLoSMujyRh9WZNwYkRUnmoE6l54UUPukiu9A+fVMGgBsGtvoU5y7D4vhTkrAm7zElvLIHK/DmRby8Fl3xtN7hLNmZSfoeY88t0B/xlVXQw3Puylqkskt8ygBz/UvEV+t3KtF7g2jirrwPejnhwzP6CCkvymxsHuTUf7u64XIZk4u9v7WSq4YVRCWxF4sGCiMAH84x+0cYF4M4TiTTNmkoQUXSENQ4rRaSQCkaQtJ6W0pb3sgTWv40FvLjYv47jn2Yxqn0fY8rMTLv9knxQ1Q5T7pE217Oj6roAEuaIHCfvTPD92x6ht8lyLE8/5tJLnebalq/NlgWxLeOEyVWaBZY8VuLRNM3peJGFYx46fiEpno4GFvNeBkzFeh9S+c8fp/u6I+1OgbLZaUDTK254J3U6pB/bYso9HmGt4B7ex1/hOyrE6Fhz7Mo+YSAVCGKVxipc6d/dYfExZKLWU8NDqoqMbUEB/IWq3HUM8OFv6N5DkUdUK7g=
  on:
    branch: main
  distributions: bdist_wheel
  skip_cleanup: true
