dist: bionic
language: python
python:
- 3.9.7
install:
- pip install pipenv
script:
- echo "Skipping tests"
deploy:
  provider: pypi
  username: __token__
  password: $PYPI_PASSWORD
  on:
    branch: main
  distributions: bdist_wheel
  skip_cleanup: true
