dist: bionic
language: python
python:
- 3.9.7
install:
- pip install pipenv
script:
- echo "Skipping tests"
deploy:
  provider: pypi
  username:  __token__
  password: pypi-AgEIcHlwaS5vcmcCJDkyMzRmZWIxLTdmNzAtNDY2NC05Yjg5LTI0OTczOTQ3YjcyZgACKlszLCI4NTE1NTQ2ZS03MTYzLTQ5ZTAtYWQ1Zi01OWYxMTM4ZWMzM2QiXQAABiByxlJAQxubsEdEsTZDYqpCDLqAhRWfx0InORUMWqO6jA
  on:
    branch: main
  distributions: bdist_wheel
  skip_cleanup: true
